version: '3.8'

services:
  nemo-curator:
    image: nemo-curator:latest
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''